//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiem
    {
        public string Mamon { get; set; }
        public string MaSV { get; set; }
        public string Diem { get; set; }
    
        public virtual tblMonHoc tblMonHoc { get; set; }
        public virtual tblSinhVien tblSinhVien { get; set; }
    }
}
